//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CVInspector.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_CVINSPECTOR_FORM            101
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_CVInspectorTYPE             130
#define IDB_SIMPLEARITH                 130
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDD_FORM_ARITHMETIC             311
#define IDD_FORM_NOTAVAILABLE           312
#define IDD_FORM_NA                     312
#define IDD_FORM_OPENFILE               313
#define IDD_FORM_CVTCOLOR               314
#define IDD_FORM_BINARIZE               315
#define IDD_PARAMETER_DIALOG            316
#define IDD_FORM_MORPHOLOGY             317
#define IDD_FORM_BLUR                   318
#define IDD_FORM_RESIZE                 319
#define IDD_FORM_EDGE                   320
#define IDD_FORM_CANNY                  321
#define IDD_FORM_CROP                   322
#define IDD_FORM_SPLIT                  323
#define IDD_FORM_CONTOUR                324
#define IDD_FORM_CAPTURECAM             325
#define IDD_FORM_FLOODFILL              326
#define IDD_FORM_PYRAMID                327
#define IDD_FORM_BLOB                   328
#define IDD_FORM_HISTOGRAM              329
#define IDD_FORM_EQUALHIST              330
#define IDD_FORM_HOUGHLINE              331
#define IDD_FORM_HOUGHCIRCLE            332
#define IDD_FORM_HARRISCORNER           333
#define IDD_FORM_DFT                    334
#define IDD_FORM_MATCHTEMPLATE          335
#define IDD_FORM_PSM                    336
#define IDD_FORM_ADAPTIVETHR            337
#define IDD_FORM_REMOVEBLOBS            338
#define IDD_FORM_TIMEDELAY              339
#define IDD_FORM_FLIP                   340
#define IDD_FORM_SHITOMASICORNER        341
#define IDD_FORM_ROTATE                 342
#define IDD_FORM_FILTER2D               343
#define IDD_FORM_OFFSETTEMPLATE         344
#define IDD_FORM_FAST                   345
#define IDD_FORM_MARKED_AVG             346
#define IDD_FORM_MARKED_ADAP_THRESHOLD  347
#define IDD_FORM_JPTHRESHOLD            348
#define IDD_FORM_DIFFIMAGE              349
#define IDD_FORM_JPTHRESHOLD_AUTO       350
#define IDD_FORM_DRAW_LINE              351
#define IDD_FORM_ADAPTIVETHR_ISH        352
#define IDD_FORM_MAPPING_IMG            353
#define IDD_FORM_DISTANCE               354
#define IDD_FORM_CONTRAST               355
#define IDD_FORM_WATERSHED              356
#define IDD_FORM_DFT1                   357
#define IDD_FORM_FARSHIDTHR             358
#define IDC_IMAGEPANEL                  1000
#define IDC_OP_LIST                     1001
#define IDC_PARAMETER_PANEL             1002
#define IDC_SELECT_PATH                 1003
#define IDC_FILE_PATH                   1004
#define IDC_RADIO2                      1006
#define IDC_BLUR_TYPE1                  1006
#define IDC_METHOD1                     1006
#define IDC_BLUR_TYPE2                  1007
#define IDC_METHOD2                     1007
#define IDC_SET                         1008
#define IDC_BLUR_TYPE3                  1008
#define IDC_METHOD3                     1008
#define IDC_RADIO_CVT_TYPE1             1009
#define IDC_BLUR_TYPE4                  1009
#define IDC_METHOD4                     1009
#define IDC_RADIO_CVT_TYPE2             1010
#define IDC_BUTTON1                     1010
#define IDC_BLUR_TYPE5                  1010
#define IDC_BTN_TEACHING                1010
#define IDC_SET_ROI                     1010
#define IDC_RADIO_CVT_TYPE3             1011
#define IDC_BUTTON_TEST                 1013
#define IDC_BUTTON_APPLY                1014
#define IDC_EDIT_BIN_THR                1014
#define IDC_RADIO_BIN_TYPE1             1015
#define IDC_BUTTON_SAVE_CURRENT_IMAGE   1015
#define IDC_RADIO_BIN_TYPE2             1016
#define IDC_BUTTON_PROCESS_ALL          1016
#define IDC_RADIO_BIN_TYPE3             1017
#define IDC_BUTTON_DELETE_SELECTED_OP   1017
#define IDC_RADIO_BIN_TYPE4             1018
#define IDC_RADIO_BIN_TYPE5             1019
#define IDC_EDIT_BIN_THR_LOWER          1019
#define IDC_EDIT_2ND_IMAGE              1022
#define IDC_OPERATOR_TYPE1              1023
#define IDC_OPERATOR_TYPE2              1024
#define IDC_CHECK_OTSU                  1024
#define IDC_OPERATOR_TYPE3              1025
#define IDC_MORPH_TYPE1                 1025
#define IDC_OPERATOR_TYPE4              1026
#define IDC_MORPH_TYPE2                 1026
#define IDC_OPERATOR_TYPE5              1027
#define IDC_MORPH_TYPE3                 1027
#define IDC_OPERATOR_TYPE6              1028
#define IDC_MORPH_TYPE4                 1028
#define IDC_MORPH_TYPE5                 1029
#define IDC_OPERATOR_TYPE7              1029
#define IDC_MORPH_TYPE6                 1030
#define IDC_OPERATOR_TYPE8              1030
#define IDC_MORPH_TYPE7                 1031
#define IDC_OPERATOR_TYPE9              1031
#define IDC_EDIT_KERNEL_SIZE            1032
#define IDC_EDIT_ANCHOR_X               1033
#define IDC_CHECK_INSERT                1033
#define IDC_EDIT_ANCHOR_Y               1034
#define IDC_EDIT_SCALE                  1034
#define IDC_EDIT_ITERATION_NO           1035
#define IDC_EDIT_GAUSSIAN_SIGMA         1035
#define IDC_EDIT_DELTA                  1035
#define IDC_EDIT_NEIGHBOR               1035
#define IDC_EDIT_BILATERAL_SIGMA_COLOR  1036
#define IDC_EDIT_NEWSIZE_X              1036
#define IDC_EDIT_DX                     1036
#define IDC_EDIT_KERNEL_SIZEY           1036
#define IDC_EDIT_BILATERAL_SIGMA_SPACE  1037
#define IDC_EDIT_NEWSIZE_Y              1037
#define IDC_EDIT_DY                     1037
#define IDC_EDIT_NEWRATIO_X             1038
#define IDC_EDIT_KERNEL_X               1038
#define IDC_EDIT_NEWRATIO_Y             1039
#define IDC_EDIT_KERNEL_Y               1039
#define IDC_RESIZE_INTER_TYPE1          1040
#define IDC_RESIZE_INTER_TYPE2          1041
#define IDC_EDGE_TYPE1                  1041
#define IDC_RESIZE_INTER_TYPE3          1042
#define IDC_EDGE_TYPE2                  1042
#define IDC_EDIT_THR1                   1042
#define IDC_RESIZE_INTER_TYPE4          1043
#define IDC_EDGE_TYPE3                  1043
#define IDC_EDIT_THR2                   1043
#define IDC_EDIT_LEFT                   1043
#define IDC_RESIZE_INTER_TYPE5          1044
#define IDC_EDIT_APERTURE               1044
#define IDC_EDIT_TOP                    1044
#define IDC_EDIT_RIGHT                  1045
#define IDC_EDIT_BOTTOM                 1046
#define IDC_SPIN_LEFT                   1047
#define IDC_SPIN_TOP                    1048
#define IDC_CHANNEL1                    1048
#define IDC_SPIN_RIGHT                  1049
#define IDC_CHANNEL2                    1049
#define IDC_MODE1                       1049
#define IDC_SPIN_BOTTOM                 1050
#define IDC_CHANNEL3                    1050
#define IDC_MODE2                       1050
#define IDC_CHANNEL4                    1051
#define IDC_MODE3                       1051
#define IDC_MODE4                       1052
#define IDC_EDIT_LINEWIDTH              1053
#define IDC_EDIT_LINETYPE               1054
#define IDC_EDIT_CAMERANO               1054
#define IDC_EDIT_MIN_THR                1054
#define IDC_EDIT_LINETYPE2              1055
#define IDC_EDIT_MAXVALUE               1055
#define IDC_EDIT_IMGWIDTH               1055
#define IDC_EDIT_UPPERDIFF              1055
#define IDC_EDIT_MAX_THR                1055
#define IDC_EDIT_CAMERANO3              1056
#define IDC_EDIT_IMGHEIGHT              1056
#define IDC_EDIT_LOWERDIFF              1056
#define IDC_EDIT_MIN_DIST               1056
#define IDC_EDIT_BGIMAGENO              1056
#define IDC_CHECK_USE_FIXED_RANGE       1057
#define IDC_EDIT_BGIMAGENO2             1057
#define IDC_PYRTYPE1                    1058
#define IDC_PYRTYPE2                    1059
#define IDC_SIZEX                       1060
#define IDC_SIZEY                       1061
#define IDC_EDIT_THR_STEP               1061
#define IDC_EDIT_MIN_REPEATABILITY      1062
#define IDC_FILTER_BY_COLOR             1063
#define IDC_EDIT_MIN_REPEATABILITY2     1064
#define IDC_EDIT_HIST_SIZE              1064
#define IDC_FILTER_BY_AREA              1065
#define IDC_EDIT_HIST_RANGE_L           1065
#define IDC_EDIT_MIN_AREA               1066
#define IDC_EDIT_HIST_RANGE_H           1066
#define IDC_EDIT_MAX_AREA               1067
#define IDC_INPUT_IMG_NO                1067
#define IDC_FILTER_BY_CIRCULARITY       1068
#define IDC_EDIT_MIN_WIDTH              1068
#define IDC_EDIT_MIN_CIRCULARITY        1069
#define IDC_EDIT_MIN_HEIGHT             1069
#define IDC_EDIT_MAX_CIRCULARITY        1070
#define IDC_EDIT_RHO                    1070
#define IDC_EDIT_THETA                  1071
#define IDC_EDIT_THRESHOLD              1072
#define IDC_EDIT_MAX_WIDTH              1072
#define IDC_EDIT_MIN_LINE_LENGTH        1073
#define IDC_EDIT_MAX_HEIGHT             1073
#define IDC_FILTER_BY_CIRCULARITY2      1074
#define IDC_EDIT_MAX_LINE_GAP           1074
#define IDC_EDIT_MIN_INERTIA            1075
#define IDC_EDIT_MAX_RADIUS             1075
#define IDC_EDIT_MAX_INERTIA            1076
#define IDC_EDIT_ACCU_RES               1076
#define IDC_EDIT_PARAMETER1             1077
#define IDC_EDIT_PARAMETER2             1078
#define IDC_EDIT_MIN_RADIUS             1079
#define IDC_EDIT_PARAMETERK             1080
#define IDC_EDIT_NONMAXSIZE             1081
#define IDC_MAGNIFY_CROPAREA            1082
#define IDC_EDIT_MARKERSIZE             1082
#define IDC_SHOW_SCALEDIMG              1083
#define IDC_EDIT_MARKERCOLOR_R          1083
#define IDC_INV                         1084
#define IDC_EDIT_MARKERCOLOR_G          1084
#define IDC_MATCHTEMPLATE_TYPE          1085
#define IDC_EDIT_MARKERCOLOR_B          1085
#define IDC_MATCHTEMPLATE_TYPE2         1086
#define IDC_MATCHTEMPLATE_TYPE3         1087
#define IDC_MATCHTEMPLATE_TYPE4         1088
#define IDC_MATCHTEMPLATE_TYPE5         1089
#define IDC_MATCHTEMPLATE_TYPE6         1090
#define IDC_EDIT_TEMPLATE_IMG_NO        1091
#define IDC_SPIN_MOVE_LR                1092
#define IDC_SPIN_MOVE_UD                1093
#define IDC_EDIT_TEMPLATE_IMG_NO3       1093
#define IDC_EDIT_BLOCKSIZE_Y            1093
#define IDC_PSM_SUBTRACT_TYPE           1094
#define IDC_EDIT_C_VALUE                1094
#define IDC_PSM_SUBTRACT_TYPE2          1095
#define IDC_EDIT_ACCUM                  1095
#define IDC_PSM_SUBTRACT_TYPE3          1096
#define IDC_EDIT_OFFSET_X               1097
#define IDC_EDIT_OFFSET_Y               1098
#define IDC_PSM_DIR                     1099
#define IDC_RADIO_ADAPTIVE_METHOD       1099
#define IDC_PSM_DIR2                    1100
#define IDC_RADIO_ADAPTIVE_METHOD2      1100
#define IDC_PSM_DIR3                    1101
#define IDC_EDIT_CONSTANT               1101
#define IDC_EDIT_BLOCKSIZE              1102
#define IDC_KEEP_ASPECT_RATIO           1102
#define IDC_EDIT_OFFSET                 1103
#define IDC_DELAY_TIME                  1105
#define IDC_RADIO_FLIP_AXIS             1106
#define IDC_DRAW_START_Y                1106
#define IDC_RADIO_FLIP_AXIS2            1107
#define IDC_EDIT_MAXCORNER              1107
#define IDC_DRAW_END_X                  1107
#define IDC_RADIO_FLIP_AXIS3            1108
#define IDC_EDIT_QUALITYLEVEL           1108
#define IDC_DRAW_END_Y                  1108
#define IDC_EDIT_MINDIST                1109
#define IDC_DRAW_LINE_WIDTH             1109
#define IDC_RADIO_FLIP_AXIS4            1109
#define IDC_CHECK_USEHARRIS             1110
#define IDC_DRAW_LINE_COLOR_B           1110
#define IDC_EDIT_ANGLE                  1111
#define IDC_DRAW_LINE_COLOR_G           1111
#define IDC_EDIT_KERNEL                 1112
#define IDC_DRAW_LINE_COLOR_R           1112
#define IDC_SHOW_MATCHED_RESULT         1114
#define IDC_RADIO_READTYPE              1115
#define IDC_RADIO_READTYPE2             1116
#define IDC_EDIT_SCALEX                 1116
#define IDC_RADIO_READTYPE3             1117
#define IDC_EDIT_SCALEY                 1117
#define IDC_EDIT_OFFSETX                1118
#define IDC_EDIT_OFFSETY                1119
#define IDC_EDIT_TEMPLATE_PATH          1120
#define IDC_EDIT_OFFSETY2               1121
#define IDC_EDIT_TYPE                   1121
#define IDC_CHECK_NONMAXIMASUPRESSION   1122
#define IDC_EDIT_MARK_IMG_NO            1123
#define IDC_EDIT_BLOCKSIZE_X            1124
#define IDC_MARKED_ADAP_THR_TYPE        1125
#define IDC_MARKED_ADAP_THR_TYPE2       1126
#define IDC_MARKED_ADAP_THR_TYPE3       1127
#define IDC_EDIT_BIN_THR_UPPER          1128
#define IDC_DIFFIMG_TYPE1               1128
#define IDC_RADIO_JPTHR_TYPE1           1129
#define IDC_DIFFIMG_TYPE2               1129
#define IDC_RADIO_JPTHR_TYPE2           1130
#define IDC_RADIO_JPTHR_TYPE3           1131
#define IDC_RADIO_JPTHR_TYPE4           1132
#define IDC_DIFFIMG_X                   1133
#define IDC_DIFFIMG_Y                   1134
#define IDC_DIFFIMG_TYPE                1135
#define IDC_EDIT_ALPHA                  1136
#define IDC_EDIT_BETA                   1137
#define IDC_RADIO_JPTHRAUTO_DIR         1138
#define IDC_EDIT_BETA2                  1138
#define IDC_EDIT_GAMA                   1138
#define IDC_RADIO_JPTHRAUTO_DIR2        1139
#define IDC_EDIT_STDDEV                 1140
#define IDC_DRAW_START_X                1141
#define IDC_RADIO_MAPINGIMG_TYPE1       1143
#define IDC_RADIO_MAPINGIMG_TYPE2       1144
#define IDC_DISTANCE_TYPE1              1145
#define IDC_DISTANCE_TYPE2              1146
#define IDC_DISTANCE_TYPE3              1147
#define IDC_EDIT_MARKSIZE               1148
#define IDC_EDIT1                       1150
#define IDC_MASK_IMGNO                  1150
#define IDC_CHECK_USE_CONVEXHULL        1151
#define IDC_EDIT_MAP_DIST               1152
#define IDC_EDIT_MAP_THR                1153
#define IDC_EDIT_MAP_ALPHA              1154
#define IDC_EDIT_MAP_BETA               1155
#define IDC_COMBO1                      1156
#define IDC_COMBO_LIGHT                 1156
#define IDC_COMBO_SHAPE_STRUCTUE        1156
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_ADD_IMAGE                    32771
#define ID_32772                        32772
#define ID_SUB_IMAGE                    32774
#define ID_AND_IMAGE                    32775
#define ID_OR_IMAGE                     32776
#define ID_XOR_IMAGE                    32777
#define ID_INVERT_IMAGE                 32778
#define ID_CONVERT_COLOR                32779
#define ID_BINARYZE                     32780
#define ID_BINARIZE                     32780
#define ID_RESIZE                       32781
#define ID_ARITHMETIC                   32782
#define ID_MORPHOLOGY                   32783
#define ID_BLUR                         32784
#define ID_OPENIMAGEFILE                32785
#define ID_CAPTURE_CAM                  32786
#define ID_EDGE                         32787
#define ID_CANNY                        32788
#define ID_CROP                         32789
#define ID_SPLIT                        32790
#define ID_CONTOUR                      32791
#define ID_FLOODFILL                    32792
#define ID_PYRAMID                      32793
#define ID_BLOB                         32794
#define ID_HISTOGRAM                    32795
#define ID_EQUAL_HIST                   32796
#define ID_DIO                          32797
#define ID_SERIAL_PORT                  32798
#define ID_TIME_DELAY                   32799
#define ID_HW_SETTING                   32800
#define ID_FUNC1                        32800
#define ID_HOUGH_LINE                   32801
#define ID_HOUGH_CIRCLE                 32802
#define ID_HARRIS_CORNER                32803
#define ID_DFT                          32804
#define ID_ADAPTIVE_THR                 32804
#define ID_MATCH_TEMPLATE               32805
#define ID_PATTERN_SHIFT                32806
#define ID_ADAPTIVE_THRESHOLD           32807
#define ID_REMOVE_SMALL_BLOB            32808
#define ID_REMOVE_BLOBS                 32808
#define ID_FLIP                         32809
#define ID_SHITOMASI_CORNER             32810
#define ID_ROTATE                       32811
#define ID_FILTER                       32812
#define ID_OFFSET_LINE                  32814
#define ID_OFFSET_CORNER                32815
#define ID_OFFSET_TEMPLATE              32816
#define ID_FUNC2                        32818
#define ID_FUNC3                        32819
#define ID_FUNC4                        32820
#define ID_FUNC5                        32821
#define ID_FUNC6                        32822
#define ID_FAST                         32823
#define ID_BUTTON2                      32824
#define ID_DRAW_LINE                    32824
#define ID_CONVEXHULL                   32824
#define ID_MARKED_AVG                   32825
#define ID_BUTTON3                      32826
#define ID_DRAW_CIRCLE                  32826
#define ID_FARSHID                      32826
#define ID_BUTTON4                      32827
#define ID_DRAW_RECTANGLE               32827
#define ID_BUTTON5                      32828
#define ID_JPTHRESHOLD                  32828
#define ID_BUTTON6                      32829
#define ID_DIFFIMAGE                    32829
#define ID_BUTTON7                      32830
#define ID_JPTHRESAUTO                  32830
#define ID_MARKED_ADAP_THR              32831
#define ID_DRAW_TEXT                    32832
#define ID_ADAPTIVETHR_ISH              32833
#define ID_MAPPING_IMAGE                32834
#define ID_DISTANCETRANSFORM            32835
#define ID_WATERSHED                    32836
#define ID_CONTRAST                     32837
#define ID_FARSHID_THR                  32838

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        348
#define _APS_NEXT_COMMAND_VALUE         32838
#define _APS_NEXT_CONTROL_VALUE         1157
#define _APS_NEXT_SYMED_VALUE           311
#endif
#endif
